# Generated by Django 3.2.7 on 2021-09-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='programId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
