# Generated by Django 3.2.7 on 2021-09-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_channel_programid'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['word'], name='core_word_word_dc2883_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['lemme'], name='core_word_lemme_9f3e73_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['dateTime'], name='core_word_dateTim_6efb32_idx'),
        ),
    ]
