# Generated by Django 3.2.7 on 2021-09-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210912_0028'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='word',
            name='core_word_lemme_9f3e73_idx',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='lemme',
            new_name='lemma',
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['lemma'], name='core_word_lemma_bc7eaa_idx'),
        ),
    ]
