# Generated by Django 4.0.3 on 2022-05-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_word_core_word_channel_83e499_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
